name: Fly Deploy
on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event_name == 'push' && ! contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #- name: Deploy success
      #  uses: rjstone/discord-webhook-notify@v1
      #  if: ${{ success() }}
      #  with:
      #    severity: info
      #    description: Deploy succeeded!
      #    details: Successfully deployed to fly.io
      #    webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
