name: Periodic health check

#on:
#  schedule:
#    - cron:  '0,30 * * * *'

on:
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check URL
        uses: jtalk/url-health-check-action@v3
        url: https://poke-stack-open.fly.dev
        max-attempts: 3
        retry-delay: 5s
